### PR TITLE
Implemented TS version of Richards driver

### PR DESCRIPTION
**Pull request by ghammond86**

### CODE REVIEW

**Review by bishtgautam — APPROVED** [review]

**Comment by bishtgautam** [comment]
@ghammond86 Thanks for rebasing the branch. Does this PR replace PR #81?

**Comment by ghammond86** [comment]
> @ghammond86 Thanks for rebasing the branch. Does this PR replace PR #81?

**Comment by ghammond86** [comment]
Correct.  This superceds PR #81

**Comment by bishtgautam** [comment]
@ghammond86 It seems that the `-time_integration_method TS` in parallel is failing but the serial test is passing. How about we remove the failing test to get this PR merged and open a new issue about the failing test?

**Pull request merged**
