### PR TITLE
Adds regression testing framework

### LINKED ISSUE #8: Add regression testing framework
Implement a regression testing framework based on PFLOTRAN's regression testing framework

### PR DESCRIPTION
**Pull request by bishtgautam**
- Adds the capability in TDycore to save an output variable in a
  regression file. Presently, only the solution returned by PETSc is
  saved and it is assumed that the solution correspond to liquid pressure.
- A regression testing framework is implemented based on PFLOTRAN's
  regression testing framework. The `regression_tests/regression_tests.py`
  is called individually for different executables reside within the ` demo/`.

Fixes #8

### CODE REVIEW

**Comment by bishtgautam** [comment]
This PR is still a work-in-progress (WIP) and I have opened it to give you a heads up. Presently, the ability to save a regression file is only implemented in C and I need to extend it to Fortran.

**Comment by bishtgautam** [comment]
This PR is ready for integration.
@nocollier, Presently I have only added two tests (a serial and parallel) for steady and transient demos
- [serial test for `steady`](https://github.com/TDycores-Project/TDycore/pull/10/files#diff-fd2b6fc8471ec87ac74ccaf0133040c2R9)
- [parallel test for `steady`](https://github.com/TDycores-Project/TDycore/pull/10/files#diff-fd2b6fc8471ec87ac74ccaf0133040c2R12)
- [serial test for `transient`](https://github.com/TDycores-Project/TDycore/pull/10/files#diff-ffdd468b3f4f5672d04cd7c1186a62c3R9)
- [parallel test for `transient`](https://github.com/TDycores-Project/TDycore/pull/10/files#diff-ffdd468b3f4f5672d04cd7c1186a62c3R12
)

When you get a chance, could you add additional regression tests in my branch that you think are appropriate for `steady` and `transient` demos? This would provide some feedback on how easy/difficult is it to add new tests.

@ghammond86, When you get a chance, could you provide feedback on regression testing implementation based on PFLOTRAN's testing? The code requires at least PETSc v3.11.1 and you can build the lib and run regression tests via:
```
make
make rtest
```

**Comment by ghammond86** [comment]
Looks good to me, though mpfao-prob3-np3 is not passing on my Linux box, 

mpfao-prob3-np3...
    cd /home/gehammo/software/TDycore/demo/mpfao
    mpiexec -np 3 /home/gehammo/software/TDycore/demo/mpfao/mpfao -malloc 0 -successful_exit_code 86 -problem 3 -tdy_regression_test -tdy_regression_test_num_cells_per_process 2 -tdy_regression_test_filename mpfao-prob3-np3
    # mpfao-prob3-np3 : run time : 0.10 seconds
    diff mpfao-prob3-np3.regression.gold mpfao-prob3-np3.regression
    FAIL: Liquid Pressure:Min : 4.65500182282e-06 > 1e-12 [relative]
    FAIL: Liquid Pressure:Max : 4.21984649937e-07 > 1e-12 [relative]
    FAIL: Liquid Pressure:1 : 0.436101069829 > 1e-12 [relative]
    FAIL: Liquid Pressure:0 : 0.947333335333 > 1e-12 [relative]
    FAIL: Liquid Pressure:3 : 0.820618259125 > 1e-12 [relative]
    FAIL: Liquid Pressure:2 : 0.751053231849 > 1e-12 [relative]
    FAIL: Liquid Pressure:5 : 0.35855734322 > 1e-12 [relative]
    FAIL: Liquid Pressure:4 : 0.295242507763 > 1e-12 [relative]
    FAIL: Liquid Pressure:Mean : 1.59981863819e-07 > 1e-12 [relative]
mpfao-prob3-np3... failed.

**Comment by bishtgautam** [comment]
I have opened #11 and suspect the parallel implementation of MPFA-O has a bug.

**Pull request merged**
