### PR TITLE
Fixes the TPF and BDM tests

### PR DESCRIPTION
**Pull request by bishtgautam**
Adds the missing `-tdy_method <tpf|bdm>` in the test configuration
file

### CODE REVIEW

**Comment by bishtgautam** [comment]
@nocollier Don't merge it as it seems the BDM fails for few tests.

**Comment by bishtgautam** [comment]
The PR is good to go now. We are expected to have >90% code coverage!!!

**Comment by nocollier** [comment]
Nice man, I wonder if the missing coverage are debugging functions that I only use when implementing things.

**Comment by bishtgautam** [comment]
There are a bunch of functions in [tdycoremesh.c](https://codecov.io/gh/TDycores-Project/TDycore/src/master/src/tdycoremesh.c) for outputting info about the mesh for MPFA-O. Those functions aren't currently tested. Need to add a command line option so one can output the mesh and then update a test to include that option.

**Pull request merged**
