### PR TITLE
Tdyperfplot: automatic plotting of scaling studies

### PR DESCRIPTION
**Pull request by jeff-cohere**
This is still kind of rough, but I wanted to get it in front of you because I'm doing some things to the timers/profiling subsystem.

There's a new `tdyperfplot` script in the `tools/` directory that takes a set of `.csv` files generated by the dycore and attempts to construct one or more scaling-study plots for them. The plots are modeled after [this one](https://github.com/TDycores-Project/TDycore-AGU-Dec-2019/blob/master/figures/SPE_N50.pdf), with the y axis replaced by "throughput" (in the form of ncells/time). Basically, you type:

```
tdyperfplot *.csv
```

or, if you want to see timings for a specific stage (like "TDycore Setup"):

```
tdyperfplot -s "TDycore Setup" *.csv
```

and, as long as you have matplotlib installed on your system, it pops up a number of interactive figures equal to the number of different problem sizes in the set of CSV profiles. That's it.

## How Does It Work?

I've embedded 3 rows at the bottom of PETSc's CSV profile report that contain metadata used by `tdyperfplot`. The first row is just a METADATA delimiter. The second has column names for metadata. The third has the metadata itself. The metadata of interest is the mode, method, number of processes, and number of cells (summed over the entire domain). This allows `tdyperfplot` to automatically compute throughputs, figure out what figure to plot data in, colors, sizes, etc.

It's pretty basic plotting, but we can make it as fancy as we like. I decided not to use pandas for this because I'm not really into spreadsheets, but we can make other tools that explore other things that might use that kind of stuff.

## Enhancements to tdyprof

Before I started working on `tdyperfplot`, I made some enhancements to `tdyprof` after learning more about PETSc's profiling system. It has some new features, generates reports faster, and doesn't include any duplicate events anymore.

## Bugfixes

Also, I fixed some function declarations for some mesh utilities. I should probably squash some of these commits.

I'll try to fancy up the plotting a little bit more and post a pic, and if no one objects to any of this, I'll document it in the Wiki.

### CODE REVIEW

**Comment by jeff-cohere** [comment]
Hmm. I seem to have broken regression testing with these changes. The regression tests are complaining about not finding the regression test inputs. For example:

```
===============================================================================
Running tests from 'mpfao.cfg':
--------------------------------------------------
----------------------------------------
mpfao-prob1... 
    cd /home/jeff/projects/pnnl/TDycore/demo/mpfao
    /home/jeff/projects/pnnl/TDycore/demo/mpfao/mpfao -malloc 0 -successful_exi
    # mpfao-prob1 : run time : 0.10 seconds

FAIL: could not find regression test file 'mpfao-prob1.regression'. Please
    check the standard output file for errors.
```

Does this look familiar to anyone?

(No hurry, I know we're all thinking about ESMD at the moment!)

**Comment by jeff-cohere** [comment]
I think this is fixed now. At length, we may want to back away from this approach, especially if we see ourselves making executables with more than one instance of our TDy object in them, since the measure of throughput is computed from the number of cells in the most-recently-created TDy. But for now I think we have other things to worry about.

**Comment by jedbrown** [comment]
In that case, the profiling data could be associated with the `TDy` (perhaps create a stage per `TDy`).

**Comment by bishtgautam** [comment]
@jeff-cohere Is this ready to be merged or you still working on it?

**Comment by jeff-cohere** [comment]
> @jeff-cohere Is this ready to be merged or you still working on it?

This is ready to be merged. I looked at rebasing against master--looks like there are a handful of nontrivial conflicts because of the age of the branch. I'm happy to try to do that or to merge in master (safer, but messier).

**Comment by bishtgautam** [comment]
There is no need to rebase. If you want to merge, go ahead. Otherwise I'll merge it tomorrow.

**Comment by jeff-cohere** [comment]
If you approve the PR, I'll go ahead and merge it.

**Review by bishtgautam — APPROVED** [review]

**Pull request merged**
