### PR TITLE
Fixes Dirichlet boundary condition for TPF

### PR DESCRIPTION
**Pull request by bishtgautam**
- Fixes the computation of transmissibility matrix for edge cells
- Fixes the computation of jacobian for edge cells
- Correctly uses of density and derivative of density for boundary cells
- Removed the use of hardcoded material properties

### CODE REVIEW

**Comment by bishtgautam** [comment]
@jeff-cohere The code is compiling for me on Ubuntu 20.04 + gcc 9.3.0 and I'm not sure why the code is failing on Github actions. Can you check if the code compiles correctly for you?

**Comment by bishtgautam** [comment]
I broke few tests and am working on fixing them.

**Comment by jeff-cohere** [comment]
Hey @bishtgautam ,

Try building with `make V=1 codecov=1` like the GitHub action does. The library builds, but if you build the `demo` directory, you'll probably see the internal compiler error we've been encountering:

```
make V=1 codecov=1 -j       # should be okay
cd demo
make V=1 codecov=1 -j
...
/home/jeff/projects/pnnl/TDycore/demo/transient/transient_snes_mpfaof90.F90:108:0:

  108 |   use tdycore
      |
internal compiler error: in coverage_begin_function, at coverage.c:656
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
make[1]: *** [/home/jeff/projects/pnnl/petsc/lib/petsc/conf/rules:286: transient_snes_mpfaof90.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by bishtgautam** [comment]
@jeff-cohere Thanks for info. I will debug this error.

**Comment by jeff-cohere** [comment]
I'm not sure it can be debugged--I suspect it's the same thing we're hitting with #152.

If we wanted to get past this before GCC 11 is widely available, we could disable code coverage on Fortran executables.

**Comment by bishtgautam** [comment]
@jeff-cohere I have disabled the build of F90 with `codecov=1`.

**Comment by jeff-cohere** [comment]
Great! Anything you'd like me to look at in particular for this PR?

**Review by jeff-cohere — APPROVED** [review]
Looks good.

**Pull request merged**
