### PR TITLE
refactored TDyIO to include exodus

### PR DESCRIPTION
**Pull request by ghammond86**
This is the rebased and squashed version of Rosie's updates

### CODE REVIEW

**Review by leorosie — COMMENTED** [review]
Did we want to add the wrapper for the cell labels?

**Comment by bishtgautam** [comment]
Is one of a test using the new I/O capability?

**Review by bishtgautam — APPROVED** [review]

**Comment by ghammond86** [comment]
> Did we want to add the wrapper for the cell labels?

Yes.

**Comment by ghammond86** [comment]
> Is one of a test using the new I/O capability?

Since our testing harness lacks the ability to compare .exo formats, I don't know that a test helps other than to prove that the simulation ran to completion.  What do you think?

**Comment by bishtgautam** [comment]
With the new test we will make sure that new PRs don't break current I/O capability. Also, the will provide an example of how to use the new I/O.

**Comment by ghammond86** [comment]
> > Did we want to add the wrapper for the cell labels?
> 
> Yes.

I will add the wrapper.

**Comment by ghammond86** [comment]
> With the new test we will make sure that new PRs don't break current I/O capability. Also, the will provide an example of how to use the new I/O.

I looked into this further.  The Exodus output is hardwired to the file 'out.exo' in the richards_driver executable.  There are no command line arguments to test.  I recommend that we add some command line arguments for setting the format, output filename and perhaps variable names and frequency.  At that point, add a few tests.  @leorosie can work on this.

**Pull request merged**
